configs:
  cm:
    timeout.reconciliation: 30s
  params:
    server.insecure: true
    
server:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: gj2025-argo-internal-nlb
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-target-node-labels: node=addon
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    type: LoadBalancer
    loadBalancerClass: service.k8s.aws/nlb