apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gj-store
  namespace: skills
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: gj-secrets