apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://<YOUR_USERNAME>.github.io/day2-product/charts
      chart: app
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/values/dev.values.yaml
    - repoURL: https://github.com/<YOUR_USERNAME>/day2-product
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://<YOUR_USERNAME>.github.io/day2-product/charts
      chart: app
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/values/prod.values.yaml
    - repoURL: https://github.com/<YOUR_USERNAME>/day2-product
      targetRevision: prod
      ref: values
  destination:
    name: prod-cluster
    namespace: app
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
