name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: app-repo
  TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Update image tag in deploy.yaml
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        sed -i "s|image:.*|image: $IMAGE_URI|" manifest/deploy.yaml

    - name: Commit and Push updated deploy.yaml
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add manifest/deploy.yaml
        git commit -m "Update image to ${{ github.sha }}" || echo "Nothing to commit"
        git pull --rebase origin main
        git push origin HEAD:main