apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: product
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: product
      autoPromotionEnabled: false