apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080