apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
  namespace: wsk25
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      terminationGracePeriodSeconds: 50
      nodeSelector:
        role: app
      tolerations:
      - key: role
        operator: Equal
        value: app
        effect: NoSchedule
      serviceAccountName: access-secrets
      containers:
      - name: wsk1-grapp
        image: 942035140074.dkr.ecr.ap-northeast-2.amazonaws.com/wsk1/grapp:v1.0.0
        envFrom:
        - secretRef:
            name: db-secret
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 8080
      topologySpreadConstraints:
      - maxSkew: 1
        minDomains: 2
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            role: app