apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: red-ingress
  namespace: wsk25
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: red-alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/target-node-labels: role=app
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /red
            pathType: Exact
            backend:
              service:
                name: wsk-red-svc
                port:
                  number: 80
          - path: /health
            pathType: Exact
            backend:
              service:
                name: wsk-red-svc
                port:
                  number: 80