apiVersion: v1
entries:
  app:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-09-17T23:03:09.813865+09:00"
    description: A Helm chart for product application
    digest: 5fd70148cf9ee1c5e6a0b069f665c2b65903d5247bb1c25fad0c8f0d7b9baf90
    name: app
    type: application
    urls:
    - app-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-17T23:03:09.813163+09:00"
